# Santiago Correa Marulanda 1033486496
# PRIMER PUNTO

In [1]:
import pandas as pd
import numpy as np
import missingno as msno
from sklearn.impute import SimpleImputer
from difflib import get_close_matches
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Pedro', None, 'Marta', 'Luis', 'Sofía'],
    'Edad': [25, np.nan, 35, 29, -5, 25, None],
    'Ciudad': ['Bogotá', 'Medellín', None, 'Medellín', 'Cali', 'Bogotá', 'Cali'],
    'Ingreso': [3500, 4800, np.nan, 5200, 5100, np.nan, 4700],
    'FechaIngreso': ['2023-01-01', '2023-01-05', None, '2023-01-10', '2023-01-12', None, '2023-01-15']
})

In [3]:
df

  Nombre  Edad    Ciudad  Ingreso FechaIngreso
0    Ana  25.0    Bogotá   3500.0   2023-01-01
1   Luis   NaN  Medellín   4800.0   2023-01-05
2  Pedro  35.0      None      NaN         None
3   None  29.0  Medellín   5200.0   2023-01-10
4  Marta  -5.0      Cali   5100.0   2023-01-12
5   Luis  25.0    Bogotá      NaN         None
6  Sofía   NaN      Cali   4700.0   2023-01-15

In [4]:
for col in df.columns:
  print(df[col].unique())

['Ana' 'Luis' 'Pedro' None 'Marta' 'Sofía']
[25. nan 35. 29. -5.]
['Bogotá' 'Medellín' None 'Cali']
[3500. 4800.   nan 5200. 5100. 4700.]
['2023-01-01' '2023-01-05' None '2023-01-10' '2023-01-12' '2023-01-15']

In [6]:
df['Ingreso'] = df['Ingreso'].fillna(df['Ingreso'].median())
df['Nombre'] = df['Nombre'].fillna(df['Nombre'].mode()[0])
df['Ciudad'] = df['Ciudad'].fillna(df['Ciudad'].mode())
df['FechaIngreso'] = df['FechaIngreso'].fillna(df['FechaIngreso'].mode()[0])
df['FechaIngreso'] = pd.to_datetime(df['FechaIngreso'], errors='coerce')
df['Edad'] = df['Edad'].apply(lambda x: (df['Edad'].median()) if x < 0 else x)
df['Edad'] = df['Edad'].fillna(df['Edad'].median())
df

  Nombre  Edad    Ciudad  Ingreso FechaIngreso
0    Ana  25.0    Bogotá   3500.0   2023-01-01
1   Luis  25.0  Medellín   4800.0   2023-01-05
2  Pedro  35.0  Medellín   4800.0   2023-01-01
3   Luis  29.0  Medellín   5200.0   2023-01-10
4  Marta  25.0      Cali   5100.0   2023-01-12
5   Luis  25.0    Bogotá   4800.0   2023-01-01
6  Sofía  25.0      Cali   4700.0   2023-01-15

# SEGUNDO PUNTO

In [7]:
df = pd.DataFrame({
    'ID': [101, 102, 102, 103, 104, 104, 104],
    'Nombre': ['Ana', 'Luis', 'Luis', 'Marta', 'Carlos', 'Carlos', 'Carlos'],
    'Edad': [25, 30, 30, 29, 40, 40, 41],
    'Ciudad': ['Bogotá', 'Cali', 'Cali', 'Medellín', 'Cali', 'Cali', 'Cali'],
    'FechaRegistro': ['2023-01-01', '2023-01-05', '2023-01-05', '2023-01-10',
                    '2023-01-15', '2023-01-15', '2023-01-16']
})

In [8]:
df

    ID  Nombre  Edad    Ciudad FechaRegistro
0  101     Ana    25    Bogotá    2023-01-01
1  102    Luis    30      Cali    2023-01-05
2  102    Luis    30      Cali    2023-01-05
3  103   Marta    29  Medellín    2023-01-10
4  104  Carlos    40      Cali    2023-01-15
5  104  Carlos    40      Cali    2023-01-15
6  104  Carlos    41      Cali    2023-01-16

In [9]:
print("¿Cantidad de registros?:")
df.shape[0]

¿Cantidad de registros?:

7

In [10]:
print("¿Cuáles son los duplicados?")
print(df[df.duplicated(keep=False)])
print("¿Cuanto son exactamente?:")
print((df[df.duplicated(keep=False)]).shape[0])

¿Cuáles son los duplicados?
    ID  Nombre  Edad Ciudad FechaRegistro
1  102    Luis    30   Cali    2023-01-05
2  102    Luis    30   Cali    2023-01-05
4  104  Carlos    40   Cali    2023-01-15
5  104  Carlos    40   Cali    2023-01-15
¿Cuanto son exactamente?:
4

In [11]:
print("¿Cuántos registros debes eliminar?")
print((df[df.duplicated(keep=False)]).shape[0])

¿Cuántos registros debes eliminar?
4

In [12]:
print("¿Cuántos registros quedan después de la limpieza?")
df = df.drop_duplicates(keep='last')
df.drop(6, inplace=True)
df

¿Cuántos registros quedan después de la limpieza?

/tmp/ipython-input-3070404023.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(6, inplace=True)

    ID  Nombre  Edad    Ciudad FechaRegistro
0  101     Ana    25    Bogotá    2023-01-01
2  102    Luis    30      Cali    2023-01-05
3  103   Marta    29  Medellín    2023-01-10
5  104  Carlos    40      Cali    2023-01-15

# TERCER PUNTO

In [13]:
df = pd.DataFrame({
    'Ciudad': ['bogota', 'Bogotá', 'BOGOTA', 'bogotá', 'bogata', 'Bógota', 'BogoTa', 'Cali', 'calí', 'medellín', 'medellin']
})
df

      Ciudad
0     bogota
1     Bogotá
2     BOGOTA
3     bogotá
4     bogata
5     Bógota
6     BogoTa
7       Cali
8       calí
9   medellín
10  medellin

In [14]:
df["Ciudad"] = df["Ciudad"].str.lower()
df

      Ciudad
0     bogota
1     bogotá
2     bogota
3     bogotá
4     bogata
5     bógota
6     bogota
7       cali
8       calí
9   medellín
10  medellin

In [17]:
df["Ciudad"].iloc[7]

'cali'

In [19]:
df["Ciudad"].shape[0]

11

In [20]:
admitidas = ["cali", "medellin", "bogota"]

In [21]:
for i in range(df.shape[0]):
    ciudad = df.loc[i, "Ciudad"]


    if ciudad not in admitidas:
        match = get_close_matches(ciudad, admitidas, n=1, cutoff=0.7)
        if match:
            df.loc[i, "Ciudad"] = match[0]

df

      Ciudad
0     bogota
1     bogota
2     bogota
3     bogota
4     bogota
5     bogota
6     bogota
7       cali
8       cali
9   medellin
10  medellin

In [23]:
df.drop_duplicates(keep="last", inplace=True)
df

      Ciudad
6     bogota
8       cali
10  medellin